- name: Install some packages
  apt: state=latest name={{ item }} update_cache=yes
  with_items:
    - whois
    - libssl-dev
    - zlib1g-dev
    - libpcre3-dev
    - build-essential
    - libreadline-dev
