- name: Install some packages
  yum: state=latest name={{ item }}
  with_items:
    - openssl-devel
    - zlib-devel
    - pcre-devel
    - gcc
    - gcc-c++
    - kernel-devel
    - readline-devel
    - ncurses-devel
