- name: add user to run haproxy as
  user:
    name: "{{ haproxy_username }}"
    shell: /sbin/nologin
    createhome: no
    home: "{{ haproxy_dir }}"
  tags:
    - haproxy_user

- name: copy certbot haproxy script
  get_url:
    url: https://raw.githubusercontent.com/nuriel77/iri-playbook/master/roles/loadbalancer/files/certbot-haproxy.sh
    dest: /usr/local/bin/certbot-haproxy.sh
    mode: 0755
    force: yes
  tags:
    - certbot
