- name: add user to run haproxy as
  user:
    name: "{{ haproxy_username }}"
    shell: /sbin/nologin
    createhome: no
    home: "{{ haproxy_dir }}"
  tags:
    - haproxy_user

- name: copy certbot haproxy script
  get_url:
    url: "{{ certbox_haproxy_script_url }}"
    dest: /usr/local/bin/certbot-haproxy.sh
    mode: 0755
    force: yes
  tags:
    - certbot

- name: 'download haproxy docker image, this can take a moment...'
  docker_image:
    name: "{{ haproxy_image }}"
    tag: "{{ haproxy_tag }}"
    force: "{{ force_pull_image | default('no') }}"
  tags:
    - haproxy_image
  notify:
    - restart haproxy
