- name: set etc config dir ubuntu
  set_fact:
    etc_config_dir: default
  when: ansible_distribution == 'Ubuntu'

- name: set etc config dir centos
  set_fact:
    etc_config_dir: sysconfig
  when: ansible_distribution == 'CentOS'

- name: ensure etc haproxy dir
  file:
    path: /etc/haproxy
    state: directory
    owner: root
    group: "{{ haproxy_username }}"
    mode: 0750

- name: copy haproxy service file
  template:
    src: templates/haproxy.service.j2
    dest: /etc/systemd/system/haproxy.service
  notify:
    - restart haproxy

- name: copy whitelist file
  template:
    src: templates/whitelist.lst.j2
    dest: /etc/haproxy/whitelist.lst
    force: "{{ overwrite | default('no') }}"
  notify:
    - restart haproxy
  tags:
    - haproxy_cfg
  when:
    - haproxy_use_whitelist_file is defined
    - haproxy_use_whitelist_file|bool == True

- name: copy haproxy config
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    backup: yes
    force: "{{ overwrite | default('no') }}"
    mode: 0644
    owner: root
    group: root
  notify:
    - restart haproxy
  tags:
    - haproxy_cfg

- name: flush handlers
  meta: flush_handlers

- name: start and enable haproxy
  systemd:
    name: haproxy
    state: started
    enabled: yes
    daemon_reload: yes

- name: copy stats command file
  copy:
    src: ../shared-files/show-stat
    dest: /usr/local/bin/show-stat
    mode: 0755
  tags:
    - showstat_script
