- import_tasks: install.yml
  tags:
    - lb_install

- import_tasks: firewalld.yml
  tags:
    - lb_firewalld
  when:
    - configure_firewall is defined and configure_firewall
    - ansible_distribution == 'CentOS'

- import_tasks: ufw.yml
  tags:
    - lb_ufw
  when:
    - configure_firewall is defined and configure_firewall
    - ansible_distribution == 'Ubuntu'

- import_tasks: lb.yml
  tags:
    - lb_config

- import_tasks: uninstall.yml
  tags:
    - uninstall
    - uninstall_loadbalancer
  when: uninstall_playbook is defined and uninstall_playbook|bool == True
