- import_tasks: firewalld.yml
  tags:
    - consul_firewalld
  when:
    - configure_firewall is defined and configure_firewall
    - ansible_distribution == 'CentOS'

- import_tasks: ufw.yml
  tags:
    - consul_ufw
  when:
    - configure_firewall is defined and configure_firewall
    - ansible_distribution == 'Ubuntu'

- import_tasks: config.yml
  tags:
    - consul_config

- import_tasks: uninstall.yml
  tags:
    - uninstall
    - uninstall_consul
  when: uninstall_playbook is defined and uninstall_playbook|bool == True
