- name: stop consul
  systemd:
    name: consul
    state: stopped
    enabled: false
  ignore_errors: yes

- name: remove consul systemd file
  file:
    path: '/etc/systemd/system/consul.service'
    state: absent
  notify:
    - reload systemd

- name: remove consul related files and paths
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/var/lib/consul"
    - "/etc/consul"
    - "{{ consul_haproxy_handler }}"
    - "{{ consul_node_check }}"

- name: remove user to run consul as
  user:
    name: "{{ consul_username }}"
    state: absent

- name: remove consul container
  docker_container:
    name: consul
    state: absent
  ignore_errors: yes

- name: remove consul image
  docker_image:
    state: absent
    name: "{{ consul_image }}"
    tag: "{{ consul_tag }}"
  ignore_errors: yes
