# Haproxy docker image
haproxy_image: haproxy

# Haproxy image tag
haproxy_tag: 1.8.9

# haproxy nofile limit:
haproxy_nofile_limit: 60000

# Haproxy nameservers for dns resolution
haproxy_nameservers:
  - '8.8.8.8:53'
  - '8.8.4.4:53'

# haproxy admin socket address. Comment to disable.
haproxy_admin_address: 127.0.0.1:9999

# haproxy admin socket file. Comment to disable.
haproxy_admin_socket: /var/run/hapee-lb.sock

# Change to 0.0.0.0 to bind to all interfaces (expose remotely)
# or set to bind to a specific interface's IP address
lb_bind_address: 0.0.0.0

# This will be the external accessible port
# to which clients/wallets connect to
iri_api_port_remote: 14267

# Haproxy enable https
haproxy_https: true

# Default bind options for haproxy https
haproxy_default_bind_options: 'no-sslv3 no-tls-tickets'

# Default bind ciphers for haproxy https
haproxy_default_bind_ciphers: 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH'

# Frontend response headers for https
haproxy_https_response_headers:
  - 'Strict-Transport-Security "max-age=31536000; includeSubdomains; preload;"'
  - 'X-Frame-Options DENY'
  - 'X-Content-Type-Options nosniff'

# Haproxy stats port with https
haproxy_stats_https: false

# Load balancer max connections (all backends)
lb_max_connections: 720

# Allowed concurrent connections to all iri backends
# (pow and default)
haproxy_iri_max_connections: 360

# Allowed concurrent connections to PoW backend
max_connections_pow_backend: 180

# Allowed concurrent connection to default backend (no PoW)
max_connections_backend: 180

# Enable remote auth with password.
# This will only allow connections using basic auth.
haproxy_remote_auth: false

# Stats port for haproxy
haproxy_stats_port: 9292

# Stats bind to address
haproxy_stats_address: 127.0.0.1

# Load balancer service name (for consul service registry)
# Any IRI node service has to be registered with this name.
lb_service_name: my.loadbalancer.io

# Lua
lua_version: 5.3.4
lua_dir: '/opt/lua'

# Haproxy install data
haproxy_dir: '/opt/haproxy'
haproxy_username: haproxy
haproxy_base_version: 1.8
haproxy_min_version: 3

# Create self signed certificate for haproxy
create_selfsigned_cert: True

# If set to `false`, the list of IPs below will be
# written to the haproxy config and managed in
# the haroxy config file only. If set to `true`,
# the above file will be used to whitelist IPs.
haproxy_use_whitelist_file: True

# A list of IPs to whitelist on haproxy
# This will allow those IPs to bypass command
# regex limitations and bypass denied commands.
# The format is a yaml list, thus ['value', 'value']
# or `- value` on each new line.
haproxy_whitelist:
  - 127.0.0.1

# HAProxy docker mounts
haproxy_mounts:
  - /etc/haproxy:/usr/local/etc/haproxy:ro,Z
  - /etc/ssl:/etc/ssl:ro,Z
  - /etc/letsencrypt:/etc/letsencrypt:ro,Z
  - /dev/log:/dev/log:Z
  - /etc/localtime:/etc/localtime:ro,Z

# Commands to deny access to
haproxy_deny_regex: '(get|remove|add)Neighbors'

# Bad commands regex example
haproxy_bad_command: '\"getTransactionsToApprove\"(.*)GFCCGTGSUEVBZYFK9QNAHOVHXUMEATUFLGBZLDKMOGWCXVUZDVEJVCLLCJJ9NQOIMOLMUMFMGZSI99999'

# Certbot script for haproxy
certbox_haproxy_script_url: 'https://raw.githubusercontent.com/nuriel77/iri-playbook/master/roles/loadbalancer/files/certbot-haproxy.sh'
