consul_image: consul
consul_tag: latest
consul_username: consul
consul_config_dir: /etc/consul
consul_bin_dir: /usr/local/bin
consul_data_dir: /var/lib/consul
consul_comm_port: 8500
consul_ssl_port: 8443
consul_key_file: consul.key
consul_master_token_file: consul_master_token
consul_agent_token_file: consul_agent_token
consul_debug_level: DEBUG
default_domain: "{{ lb_service_name }}"
default_dc: my_dc
consul_dns_enabled: true
consul_watches_enabled: false
