- name: set max usage for journald
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^SystemMaxUse='
    line: "SystemMaxUse={{ journald_max_log_size | default('1000M') }}"
  tags:
    - journald
  notify:
    - restart journald

- name: Uninstall docker-py
  pip:
    name: docker-py
    state: absent

- name: install python deps via pip
  pip:
    name: "{{ item }}"
    state: forcereinstall
  with_items:
    - docker
    - docker-compose
